name: Build and deploy docs

on:
  push:
    branches:
      - main

jobs:

  build_docs:
    name: Build docs and deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ubuntu-latest-${{ env.pythonLocation }}-${{ hashFiles('**/Pipfile') }}

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pdoc3

      - name: Build docs
        run: |
          mkdir -p docs
          pdoc pypowerautomate --html -o html --force
          cp -rf html/pypowerautomate/* docs/

      - name: Deploy on gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
          CLEAN: true